apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
    labels:
        app.kubernetes.io/name: n8n
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:50+3YNdJTJBugXN67Yx7GiuxD+woENLZ3yNseeZ3VAkAKt7U+JW6cnTiodNaUgSqzg0tPqXkq1OQewoiiq417g==,iv:otcdG4Xv+GIMTAkspee9DUinS/b8rpDMHGfwnTB4ebM=,tag:2HAnc8xNaY5gTr8v3ZbsYA==,type:str]
    postgres-password: ENC[AES256_GCM,data:DdCywEReiwlpRgB4WCfAKGL9bxAF4rOpYbGXMxVTJa2nYejBgQ8Y4/P+75+V3M38,iv:FBhtXr5BkqOGZcfk+Tp2F0Gnd4I0Yj3Tv0Hore/wuzU=,tag:zXX5z2gYIIlJg0/atW6DRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4emhGMGNzVlJzUld6cW5h
            dlZVOUdCaXFQSHVIUTk5VGs0RURMczM0YVNJCjg1OVNmd1FrbXVCcUwvVFluYlJu
            d0dXa2xiV1VkSk1KMldqbnc1Z0dvTWcKLS0tIGxBOW4yaWROOU1QMjVORDgvblZp
            TWpuaG5iTU5kUno4Q1pycTRuQi9jT3cKbgmRkZbl3fPoi/dS9EHRZeh6EjkmS0hP
            GO7eYszOa97SLoManaPCFiZAUwUf86IpYoSUh1YtmH1W+7Vhxg6D2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T21:29:44Z"
    mac: ENC[AES256_GCM,data:Ai9/VsqqnOZD8ajQ7UiBd58CM55a3P9FWz7rZf9usbzy8vmECk7g1d+Djue6qfaqeaRoVbp1Q22QiNRVcTZoioJ8+kxRObwj+Cy4+CcOXV2e2Ng+MEMzvdX0XxY3/EZNs/K82GZdk8gnFJPrVRxEqksOCXrBnhJAceyg+WkwjCA=,iv:tolsKhrq6vnTfxF6QS+VQj/w4L0lPqw1HCTzU1V/TSg=,tag:GF/HbSTsQh6Pj0sUwe6gqA==,type:str]
    version: 3.13.2
