apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../03-remove-pvc
patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: ops45-mealie-files
