apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-lb-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: cilium-lb-apps
    app.kubernetes.io/part-of: fleet
    app.kubernetes.io/managed-by: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/froggyleonard/homelab-fleet
    targetRevision: main
    path: clusters/apps/platform/cilium-lb
  destination:
    name: apps
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
