apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: fleet
    app.kubernetes.io/managed-by: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/froggyleonard/homelab-fleet
    targetRevision: main
    path: clusters/apps/workloads/n8n
  destination:
    name: apps
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
