apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sparkyfitness
  namespace: argocd
  labels:
    app.kubernetes.io/name: sparkyfitness
    app.kubernetes.io/part-of: fleet
    app.kubernetes.io/managed-by: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/froggyleonard/homelab-fleet
    targetRevision: main
    path: clusters/apps/workloads/sparkyfitness
  destination:
    name: apps
    namespace: sparkyfitness
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
