apiVersion: v1
kind: Secret
metadata:
    name: plane-secrets
    namespace: plane
    labels:
        app.kubernetes.io/name: plane
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:7Sw7pJDRygssBvVqzZDlLx8X+DZp7GzAU3+j6slrkWL+aqMBZca6sOszq9E3BLGwc2M=,iv:8qJEl2h70vwVpcCgxM0gmX6FAkFoMPrSgJ3ZjwFp6Ts=,tag:Mpco6VMDAsBJNj8D/P5SBg==,type:str]
    LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:4ylbq+tpeSNg/ruEjBkIv8Ednknw5Wh5uSYwSK+kbD9JZrqjJg2EYg==,iv:fnbVnlhkemIjVC7ao3i2l3Bq/9KYsvVttV6M0r0rTOY=,tag:lOy5FhA+/SkzoeiAmZl+yQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:XvhodnB38aFcHzTcn6I4uJhybn4J3uUF9BUF5Vsdjuqxg9GUsacRuTUYAc2k6i0XJsa2T+1gHUQ6vl/hfR216aHVBRJ1zZeFSt/imjvVFI7YA8V8Dw8hRYWnA4QGr4/TmEPUD8bGz1aO2w==,iv:AaUgVyoFkzKEwyqdZOJMeskkKjpadzKAnRlwnCYbYRg=,tag:xUCqSvj0QIB3ySORD0sItw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Kugwez+Mw+bXY5wY+8F9I3U7KiIgzblpFwqN/DmA65NiSjx+xg+i5cX6vRLLDPAKTQ==,iv:SzR5KbWlsbruHv5Ma9b3OdE+6pdwYUU1fdXbBikT6vc=,tag:wIpLjqkRAJJxDNEsNc4fKw==,type:str]
    AMQP_URL: ENC[AES256_GCM,data:0IOCCV8I4TcLjxXtfCpQ2g1H6bgDZMrvKmG4IrmBbLfLUGBKy7cp6QKaJk6Pfk5tZ6OaZFxtAL9v+7cAusKqePjH8sarzmilZbNIIjkrog5BXX6bCeAULotHgHDgeVfHOM0=,iv:Sx4mHBSHFGBpbWYtoJBOxcTv+MgdoVTAdSCnI1hTgfI=,tag:eyjD7OGDFmtif0Ki8gAMPg==,type:str]
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:sWHD/ZE=,iv:T6JbJqlj6Fj09wLdUeCGNNJHYp2AZSJrFo63OzefjRo=,tag:l/7rYErqAiDT6eL5lmWk+Q==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:3N0oWh3GAUVUsYelH5BJ/mgHUQXHt0y4T591jV27g0ahR3Ef6SxXzg==,iv:N8/4r/sAqJoYGwtJfJgVSPHxsjujTr+W+uMgqCPEvyw=,tag:bAKO7eCi8RfUhaBzoBgtpw==,type:str]
    USE_MINIO: ENC[AES256_GCM,data:rg==,iv:MYTcLST0qyVFl5iRpoKNZt7zdu1qDqLuEwZNdPZMCIg=,tag:F3MXTmTnq9QKjnomoBEYpw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:wNXYL3uQUlHxRjs=,iv:ZgrfIjOSn2fTjoUiSDREJ7nnbXHmGQeoF5LWMtIKafo=,tag:Whw5voV/eKM67zaWIKUVZw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:8XKQJ41x0uBo+kgyvtix5MtVZNHmJRjYziHkiDZ7grc7/eo0Rb4KOQ==,iv:3PWHbMPE7DP5A/3PnRBwONNA00Sr36yGr/LPiIu/nSw=,tag:LFt4hrdJ47PelmbxtTSSng==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QprdQDfRCr653GI=,iv:+Mw0z+kSy22JhCOQS9Lq5jk8zgPGKH8EzQ84lkKiYIQ=,tag:CHYKszDxTbULSf/vh6gorw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ig88zMoIBEojvmAWBCojrlZQR5YtLK+NRMoPkp00uOcC7gi4qjbxCw==,iv:cTyMSjuKbiXQvVtTGlk7VPtWNN2BQvz6ZNjuwirjFcg=,tag:DX3uhMkRFZXA0Y/7z05lXA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:pwmINF4fyCSh,iv:cJ6ks95aJHq0VIiFj0Wr2ay2KaMb/RXiafHuxUuHXjg=,tag:LDFr+7r/O65zu8IpYC5B8A==,type:str]
    AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:Z0jMGs4yUA==,iv:AWxhk16pms8jeRvTC5Vp5RjXta1V98ql7mzO3LtfBW0=,tag:C/cJz3YselDlvGVgmxSF3A==,type:str]
    AWS_S3_ENDPOINT_URL: ENC[AES256_GCM,data:qMV2MVXPFwulX/7/qz9QIPYAU9wTOB2kfUjPwWCS/kL39uNdH+MWhb9T/dP7gY4=,iv:QjF0ihCt6Vtrr/3Q7yfCLTWR3S1DZ4zYv1tw4mu82Cc=,tag:LynThXNe05Ox6KtlnkuuEA==,type:str]
    FILE_SIZE_LIMIT: ENC[AES256_GCM,data:tf/VrF+A4w==,iv:pN+xoMkqQuOP0yHbZyR1GewqeYxEyg6MAt3hVdk2ols=,tag:oCfjW9v39H/62ENXr/2MsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ejEyUkhtMGdlL0lsS0lE
            cStwd0thYmpqb01tb0NNdEc0b0N6WEkyU2hnCitWME1LSlN4NVVWYkxPMHZyUWpo
            eTJZMk1Cb3FhVmN5MGlzN2JFQS9KQkUKLS0tIE9FZHVIOHpDMjZqRUk4bC9NL3hB
            OTA1emFxR0xIUGNteU16a2Q2NVpKeVkK1BccalzWlPp3SV4ftCvgZtFrrPkihTMN
            GNmH6haGcYOR0QPuHxd12qkD0i5EtkhDnpbKDBwmqm9+RuzX5wf+xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T16:58:47Z"
    mac: ENC[AES256_GCM,data:+Ki3uaoG6X5MA6NIN4dCqH5YcmHMFcrl4P5PAG9y8Sgc1JYQFe++LNKQlSX6701xECXitIxjTIxpOLgBL6aRWkqp6hislhEACokzeDOervWfyFZgQFmdOec1G7ETOTQdh4UQiMrXXmj4BGWmevr38geVF4CL6qDjtua+5kgeRwo=,iv:8GRtqp3n2gn9cEPl0tZWG1WxSMF94nqOdSZXcH8XPrA=,tag:GfQoXe8PKwMkjjDOkdVRwA==,type:str]
    version: 3.13.2
