apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: postgres
    labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:M8YgSM5XXoa7K48mKbSIBWpofCUjXouQ2cJCekWEIrwpJ2yEDjIQQPow+/ozndeL,iv:zij7C3HDg+sIAsQqk0Uv3H8Y27keRd+5mVsmup5x698=,tag:XjowVBFvrIHOmPj5RqNvqA==,type:str]
    authentik-password: ENC[AES256_GCM,data:47I9uERRo/qlO0KtqnM/yp1EVMvQ59+O1MRI+UfOMINgg+aagP/fiwya0P2riLns,iv:MtT5fb8CqwjVlIRnqh29AkRdTFoSWW7YQz3FH7IAeY4=,tag:a9jj5xAciZ6O4a1IxMXL7w==,type:str]
    n8n-password: ENC[AES256_GCM,data:msmRJhHLOHO82TrL+UWanYjEWhEDkeAU8Q4wZNtwbC+eiYQAuJKBsYVx2lKNkm4H,iv:04rkIZe6Vx7jpa0A/SOb7gLlnk3JZzkTnvi/S+fk//c=,tag:ry4YiDUFJbq9qTytf20rdw==,type:str]
    sure-password: ENC[AES256_GCM,data:Oz5NLzwAHo5GHsA/7N1tOfYiTLYkR1W0MbG8LJduDui9xdDRSI0LazXhtavUwSz7,iv:ikJFJXGZfcMS6G/QvzlcdNhSR+OJKc0VDjSdX1CTXPw=,tag:oZfaz+NR4bGhZbvxCS3b2A==,type:str]
    plane-password: ENC[AES256_GCM,data:EPs8EGSM+4eTntObNqt9RlSezBigDpxCefL5aGy1lpngDsPXJhQHTg==,iv:x1LqU1O99XWg1yLaJoP9lcBZpXmrL2ho8xWLcsgw0NI=,tag:IbiJ2kMvYI+OziCANLaWhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNjRPMFdRZ3o3dkkxK2x2
            eTNNcmZGQkY5WCt0enlHbUtYaFcrMmNRY21nCkRhRmd6MlVmTUdHcm9FbS9DS0s4
            UEcwSnFiNkJIeW4zZHUyaEJiWDNqMTQKLS0tIFZxZUszTWJubllEcVlTc3Nic2Ur
            L3dVYjlpRnBHcVNaRWhCaVFxTU1OdmMKbnsr7hr1gQ07+mqVr5s0H5A2u6tqocag
            1+3ffKpa2rmC55LiVmr6AxtlE3QjpZWRRimcf0pAvTecOyozWXIb1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T16:58:47Z"
    mac: ENC[AES256_GCM,data:ph2LSb9chqDmVH1L4VVAt9PSG1WAZB7WaFM7M5NLr6Cc9F9BKAlaE2AD6KPCscv2kkbBg8VWf0w8gVqTCl5w7Rnns2D3HwXA10JdD2vmDQY8MiG+a2qSL5rTRmJOu+9azGIvUdHLX6xYVBFatj54ZAs+K66tcrxWmni0pvN6MRM=,iv:BFox8vE4qnVdk9cOEjsZeZBsQOcEgZ4YU+0CUtzns+o=,tag:57pPlzeZhiTAWcHi6wAApQ==,type:str]
    version: 3.13.2
