apiVersion: v1
kind: Secret
metadata:
    name: tempo-secrets
    namespace: tempo
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ywQ91waEPAXUYy+Y3p/yLWQFqM+LLz1D6ElOeO8CLPNrEcCoXOA0lL5ihmCkiSmDKkll3vQ9XMLzmMUh+jiB7w==,iv:yoOB/5lsQpy7A+EOHN+DfztvV2fH1SsjSzOFTA06+DA=,tag:f7LjsODJteenJb91OwfYpg==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:WgsasEVXlbx/OcYz9wTczck1JHRXZbjsAE4y3l3In7/5XiH0tIxOhAFooups/soS,iv:uBAUDMEz7PfIwAp2oMFug4pOfnPJVIGJEcrJhnqp3bU=,tag:+6LpspCh1YDzNace1FkX9Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:7WPfrZndkN8EtwSt7AEPPCHx/ooo4YJ3xrPqzUzRCkfLjEzvtIkKiUHac5Kynufi1Hm5U1XvFa9/57JZNS/tbFM0fj2ut/I+NTb9Qpxa5zuiYfd7FqsRwQc0TAmTTUzSZW889CIUulqHuernfn1EqCpzgw==,iv:Eg4SdT3M4m6/Cv/IKTIGoX97ohpF7bmucmCLAZ4VEVY=,tag:QJT6SVRaug5DR40nXVokig==,type:str]
    TEMPO_API_TOKEN: ENC[AES256_GCM,data:j4KQUwM1Gu55I5gMIm4N0J+t/vDxhgH4a9xKloNY8ONIgD0mz26gx6VdVGc31MT//Am4Fk7jZupmpAibsw1L2w==,iv:3yw0FgTbCDOzja0ojEgGzrZJ36H8TYJVdJbNL5ETUy4=,tag:nAmPHUdDQI13x1C86e7QBQ==,type:str]
    OIDC_SERVER_URL: ENC[AES256_GCM,data:uBwE5QPVGJzNfMpgLctJhruWXX9721gTs1+OcIR+CxzNNM35qsHreI9QlduyZkJXSymGn1KlXNU=,iv:asiIlxO7AeHD3sIdoiPmMmUSQMXJrBiMmVhBqDpcRyc=,tag:I+JcQ8uBFRXjebJGCMYzyA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:vTddiP48e38tFpBApznx5i2S1NJCG1fK9WexPt2V0lYWi2ekjWbusg==,iv:wBODvaiMkYCo6iEEw1ru9hJtbTcPPFD8S/SPuEAnbMc=,tag:ZHgDEjJLdXR7+kp14ibIWw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:B9C1PNra1fprF/sqZj4BBJqCDscKPJQgOkG+wg4/b+KLEWe3te330irT9ZKLv6/TpzUfTTGaZF/Cnq2MEEk/layR6M8B8W32r/0s5soHJCiCpr7YjQn61X/zQltU/SupfafuOYty/DKyRyGTrig9RJnVnSJaI3b+Vw9u2J/zSpU=,iv:v82/pFp+lrvYUTC1gMTBlnXqvKiQOPnkHMeM9PLS6Eo=,tag:hZTHmZiO0BSk+ZEFz0Bqag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Zk1KTlhDd05NT3JzdW43
            S3FLSUcyN25oMzdoZFI4UFdlMUQwMjk2MG1JCkdGM2hsdVFXVXdHSkNpRXpkbnY1
            dXRFK0JRK3BGVmEyNnVyWjFjMUZzSG8KLS0tIHdJNEpVeVlKbWFjcUtUZTNHYlZ4
            R0xZMlpWaUFJdnFORzFMaDZ5bXBIdjAKKnt2p6rU+hggnNa6D2tgC96qg5JUDMVm
            ERZLLl6abi6BehWUSD9J2fBG6vWslOFX7fXT8PZfFL81tzAnszmatg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T17:41:18Z"
    mac: ENC[AES256_GCM,data:qEWL+BS2t+pJWgQhbBOrhQB0aB92/InNSvGgPFzSY4Y1d1O2JHvFDLPPYmFP3apAN+VseL297QsTbjmBq5c0XeoSNjCYRjDiJYOS5LjSRe/qEiMruX7CjywxjkG7Ui2Xe1ox8fJ6888el3B3PcWj0HEkxZrXO7/NqqpjefP5DWc=,iv:2UPoXqY6/v7N8+1npNp/pOEfCEMKr1t91/JZ4mb6xQU=,tag:FbCHTBLfKPlTQJSK0D2pTA==,type:str]
    version: 3.13.3
