apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: tempo
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Lb+HIPHtPpTo+7mgNxLex2OtDRklcBojokXuRbmVulYEvYU2qt5skP7IMVaUXBMEaJ0qVkwr6gbHnxriB8bg8rBf5CW0WglhLtghT+4ltw8ouodS1odSYr63OGuXY7wiHSPxsyKf+/4FJSU12A==,iv:YiH0unBnJm5Cio1iHiP1Z3iBsZhqkX8a2/O47OYUCPs=,tag:dxNaL2Qcvx3bYQbheCSMnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNEl4T0ZZb3NjS3ZlbGNI
            dUpIQTk2bURRQjNsOW9nZ3AxZW5EaDYwbWxjCnhhYUplMlNNQVdjSU1OazVtYkdV
            NXdjeW02c1NFTXhMSE5ybTJKbFh2RzQKLS0tIHVFTUlHNHhwVVpPVW93ajllaUUy
            L3JxWFJHb3dzRHpZdjQ4UG9wc21jdk0KbFfRf5+Wy29P0jRnXEZSjMcZVsUBHitG
            zozPqL2jKjrA/mlXNEzPubJTSv/Qal6jXu5cxQVDcxDQgwTO0OU/GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T17:41:18Z"
    mac: ENC[AES256_GCM,data:vUGVqrifcl31p0HfdN18T32R1sUb2STAZ1qFr9OsFxTSiBnV0+vxvYxE2+Dv/RWh1FUYTXJzaXvgj+mzg/eZbm7GM9TO/yoodkUEgCJrI0DdVcE/LFQaZ6wdMIjVj2sKNWawhBtSfea3kJwjedbJXh2WndXg+qi7uW+fRq0FJwE=,iv:fsn/MXiIAHxn82KvdTvs8Q8PNw893WqR2C7DPV/Ko/A=,tag:1/hk2ACK5AprT5kWXVcgHQ==,type:str]
    version: 3.13.3
