apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tempo-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - 02-secrets.sops.yaml
  - 02b-pullsecret.sops.yaml
