apiVersion: v1
kind: Secret
metadata:
    name: securo-secrets
    namespace: securo
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:NAgEZlpL4ZiApECQvMIq7pDZX8TZRQrE8HGQftmfAaLZpP4eTUfl/cwmYu/FWn6LYjYlZ0Rn5EfSObzz658qkQ==,iv:eVaulS+ns2nDE9+WznfP7TSomSvzUE7qvmBDl8mXYQg=,tag:aVhPPWEQrH8ACGq2CmC+qw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tbrFVGUAujSkHB527u2NoW8qMjG5maupb7sgJYf0Lpk=,iv:m8qPVammJKdW0a5eVNH8Ugz5k0pgWE87WNrNreISeaE=,tag:LVMJmrjISND0Uhc9Wa9CqA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:1hwCktfQCIaXf//KB0XX1cJPtA0t7+gHWNsvoB7lvtA8DX1pfLsqcIunRHRwgr7IjJGcWZfKNoBABCiic2kEAImFAmBb1IoOfd0c/sJ7rzQ06vrlXIwndN4L6Sw=,iv:kEbEU3JVkEWdHLPNY4bigUKy9qXQXTvN12rQfKeufxg=,tag:IHHZSnVU4f7O/avJKONPgA==,type:str]
    AGENTS_MCP_JWT_SECRET: ENC[AES256_GCM,data:fUhPH+hTsR+y/hArD0Kd92QEuy9wF+Mv05XudkW8e1JL2Y9onkkL7aISClTnlp/cJfiaCPZsGBthIqCc9Yx6sg==,iv:CJrQFYRORoyS02S6GxKXL+JQvUiBaZ0C8ORGCoAoyE4=,tag:tTjMjgJFS69UtrUsqp39FQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:gw/kc4d7vGEDvxkveCllpyII4VaDj/8/JUqZaGCTGuWrnn7AKV+0Rg==,iv:DIprSvQSO770fgStnQXbZnXTxo9Fe3LRO02ONyUM1II=,tag:aph5ZWmCdl9SmAJl2QXZ6g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:coFq2FYfhwouVy0md49KlVmmWrqHJA9Wl2BRNo5AgWn5UI4YT2vxrjWwx71JN818T+UYFySk7w1Dr7AQiaspM6TrsGzmPvt7mIavmVdadOegRSzZmdB0IYpb25rRZuDgdb2oyj9vY2/UXWULlLJP9Vni502aVcvQL9xnYv/4Z/8=,iv:N5Twiyd55rjoemA8mANyw0QEtxaqzebJFbh1+u2All0=,tag:x4fana7kM9lIop2XCG6UQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YzRwUGVGZnlYNGs3Q1dV
            R2EwUHEza05OenU4WHZMZm80VmRiNWgxOWxVCkVPbzVCR3ZpMU56YVo1NVVYamdM
            ZC94dTV2bnYzbUNCY1lBa29rc0VVVTQKLS0tIDFjQ3ZwWEQ3cDhVZXFSTDVhUnZO
            VENVejVxaTk0d2Q3RWE3QXU5alZGUHMKHV0MGiwVy3VjRMrCkyPsf371PXi/yncO
            EaskPF8lF1B1ugC3USRqucFgdS45KGU4B5UmybeUhGNZTOBxGNK7Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T12:47:46Z"
    mac: ENC[AES256_GCM,data:H2Y7Ls6BcnYrWY9oRIGDEGEaY9imgJr/gyrT8WdA+s+qr3lZV5tcX5fo/olVIFRo6WetcPOqlWxp/ObTGaudRVEuSKjbvW7/VFhrNAi4BsEEQ4yefPaJCE8TwwzV73+K2Cg5BGMDgkcW8ntz6UJPQi7PeIZwnmMwf61tybm3aYo=,iv:bYUEHwOYuiWBhLQXMtIqaFpt0Xaf6l9DX1mwMfd8T64=,tag:eUbTk5yZ6B5f9BHHyFzVag==,type:str]
    version: 3.13.3
