apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../04-remove-pv
patches:
- patch: |-
    $patch: delete
    apiVersion: longhorn.io/v1beta2
    kind: Volume
    metadata:
      name: ops45-mealie-files
      namespace: longhorn-system
