apiVersion: v1
kind: Secret
metadata:
    name: sure-secrets
    namespace: sure
    labels:
        app.kubernetes.io/name: sure
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:rJPWj5k4Klxm1zTuUbTaZtvpVShqMk435MAwMVjR4l/HJ/OGNxgVyJTPugCClAq4fo6P3y0m1gDj2J24iagewXddhDPMrHxaFTxV5wclasMf1N/Q4pS+298AlEdAhWI6M2B+4Ntm8WdshJHihJ7t/Vvu93Swf5Tj52FHv9/RKIk=,iv:LWRVdHVeVpGD09cnZxJ2XG6emiFzPcZk0uq1Nofvp1E=,tag:mkxanN7As5NFHgCOZk8lvw==,type:str]
    ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:1ocJxr2Ok9mcSaRgcRABCJR9RqSEzkkCGsu/AQsLlDXKh5Ox5yk13ZiRumD6Y5For+WosMdSeMBTCVQayKKlsA==,iv:00DaPOeh43zTH3LoITiYVdJIIkAm8seaKIWHHePOdgg=,tag:0wstSwdtpbu3DB7ZR1cDMQ==,type:str]
    ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:Rhn+5WzZmQrmwNweNZI3CWqFqRjUlx8vlA7gJi0DTsAEEiclFONd8k//6JKfOda/DfH7cFM+hMf1yQQgzu/amg==,iv:SR4DCfnssji1/bFE2MDu1HQjgdgMiO+obyzHcz+uOb8=,tag:/5JqfIW71RF44VqP6kN1QA==,type:str]
    ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:Cbusdy1QWyC5OVtU8MiKcEvs+TVkpTz0k02+x25Qh46PSbj6MgPoXJTk9e0kKJtsX3Zwh6PjMEOEtjO25Vzqfg==,iv:rsZdWML1BzqjVlSpO1vld15arv3r//rcIGYuhtb+qZw=,tag:Skcb6xbNSGdFnroSxqnH1g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:CCk25EsrcuGSGygnYR9xlTTyoVFhtsEEmMxbU7MlzvnXCLd6fQMEvFlKhymOF8anK7z2723pSJccVhXLRDXRbGUL0nTaYnhcoM8KDd8A+gccNc0HyXrKuaQ5u/g9d9fyXUgSAGwrQFodinRj+m8=,iv:IqeT28ULvyjc3m9GCPGzA40pK35hMMoe14sll6P/aE8=,tag:uNqk0usMWgJpemI7S+fHFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMk1UcnpKd2lpRzgrbWJK
            aFBMejdzKzA2ckxmTkRLQU1qc1NyV0tJempVCnFBTkNqbit2Y3VUb1lWdGNFVG95
            VjVkcXMrMWQ0OUlDV3R2NHhSTUhHNncKLS0tIDdpQjlmYzNuOEZ3N0NXSW5CK04r
            bi9RT0I5ZTVmSnVNS2djV2xwTG5SVXcKf0/Gv72XXkt80makKD9oRzvq3f0EtwSS
            EoHTaqr5ub12As0dxa9q+FEyFZAFhSUWifqmgPAEN5TDvQxFuPRzUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T21:29:44Z"
    mac: ENC[AES256_GCM,data:Ybfq1VV6+0lPZHv129j3nHkXXBm6/YVX6FhoVKGQkyZNX6pBPzA5BdPg1IuabCo352NtsQKASM7ZrLMQkSKDwZhK6JWxywjMRBlzQ4n6KsFKEfCdY4AH+Xmq4nq3R1fGR0Bo/yZeXgOvIj196D2J+Tn0Z21XEJ/nrv+0R54hJcI=,iv:6NrhQVfNr3DDWk1ysP10MP1oWrYHQMt0FRCWHZb6o1Y=,tag:9xAsNZeocLydkaK4CMI4EA==,type:str]
    version: 3.13.2
