apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: ops45-mealie-files
  labels:
    app.kubernetes.io/part-of: ops45-restore
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: ops45-mealie-files
    recurring-job-group.longhorn.io/default: disabled
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/sync-wave: '0'
spec:
  size: '5368709120'
  numberOfReplicas: 2
  frontend: blockdev
  dataEngine: v1
  image: docker.io/longhornio/longhorn-engine:v1.12.0
  accessMode: rwo
  staleReplicaTimeout: 30
  revisionCounterDisabled: true
  backupTargetName: default
  restoreVolumeRecurringJob: disabled
  fromBackup: UNBOUND_BACKUP_SOURCE__STOP
