apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
    namespace: sparkyfitness
    labels:
        app.kubernetes.io/name: sparkyfitness
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    pg-password: ENC[AES256_GCM,data:zsLuNUFQcKxn9dRwsmlvNYmBz4hna6DZkr1M34KABZc=,iv:7dkj/JEeWw4wEWzojhkmd1iKjASG/IXcSpA0FADbdDw=,tag:St4N7xJ9xujClOVjHY8Oag==,type:str]
    app-db-password: ENC[AES256_GCM,data:U/FZFRdjgQl6jESN79CBeC/RZu0GC0Z+5q+oTJRKZP0=,iv:MsFr+eTWifobLNJqxn7vZgYGTzi5Wor+jq0Eip+1eo0=,tag:6cWlcacoHCX692SrMreBgQ==,type:str]
    api-encryption-key: ENC[AES256_GCM,data:3AimYDzqIzNG3vd/s7QhZmAITjr7mH+GHfTZQAfNeDrNi8Egy1cwyPKvNrChKjNeZ7s7wIldfh5j8nUAjsI0HA==,iv:t6N7YT1+sanzcLXnmSVByQxKnlJTbIEuh8jLT/lh5u8=,tag:GX4xoUBNt2dn9rcWpCEcKg==,type:str]
    better-auth-secret: ENC[AES256_GCM,data:rAwMsXUybLa+WhynuLJ0fBPlJeNnySSKMIP8oh3/hUbZW79CoBzBgQ/fPSq+11cu,iv:jcef8ZWxFPh3aC6f/JfPIozx2G4ncPin2fUzfIGbTNQ=,tag:V2Xv/AQPzNOBVA/at+K0cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieFRRV0ExSXBDcFExVU5y
            VEEwKzU3K2hlYzRTeXEwUERKcE92QXNhdERVCkpCaFpIcUR3allScHhnYjFqZU1S
            MVEzcHIzRDZsaitEelEreTRpSmwzdDQKLS0tIFpjdVdoVExsL1hLSE1LaXVmZlRL
            cmZXOTVIeTBvZjhXNXNwOFMxbWZsZUEKSQzK/hMV/zSDbKvvUAyZ7FI7uwBcgWyX
            6bZM4ai7SxmVbtUZ5ReD5lSCW+XKB7VbsOS8wnyvmSV5MXD5GveP6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T01:56:19Z"
    mac: ENC[AES256_GCM,data:JQo52AIAdWYL17VMtidkH9Tr3ea5CYrl9p5H1LznwBAcxy8pLHihsmxlUsCtYhc8rwFjZiWgnrMS4MNsAxaro7W6of8vil0W6vQHWkoetgYmRQIjc9IBEKSW2yxlFwA9ILlvf+dtYlAmJTN2v0fE/9rWRaTB2PTVPdvbFIJmg9E=,iv:wzFC80MOdOBE6jeyXAOOlFwkgg+KaWZEsc2KiSu60WE=,tag:zR9arjBtH0zhIZfJAiDaBA==,type:str]
    version: 3.13.3
