apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-secrets
    namespace: sparkyfitness
    labels:
        app.kubernetes.io/name: sparkyfitness
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    pg-password: ENC[AES256_GCM,data:zsLuNUFQcKxn9dRwsmlvNYmBz4hna6DZkr1M34KABZc=,iv:7dkj/JEeWw4wEWzojhkmd1iKjASG/IXcSpA0FADbdDw=,tag:St4N7xJ9xujClOVjHY8Oag==,type:str]
    app-db-password: ENC[AES256_GCM,data:U/FZFRdjgQl6jESN79CBeC/RZu0GC0Z+5q+oTJRKZP0=,iv:MsFr+eTWifobLNJqxn7vZgYGTzi5Wor+jq0Eip+1eo0=,tag:6cWlcacoHCX692SrMreBgQ==,type:str]
    api-encryption-key: ENC[AES256_GCM,data:3AimYDzqIzNG3vd/s7QhZmAITjr7mH+GHfTZQAfNeDrNi8Egy1cwyPKvNrChKjNeZ7s7wIldfh5j8nUAjsI0HA==,iv:t6N7YT1+sanzcLXnmSVByQxKnlJTbIEuh8jLT/lh5u8=,tag:GX4xoUBNt2dn9rcWpCEcKg==,type:str]
    better-auth-secret: ENC[AES256_GCM,data:rAwMsXUybLa+WhynuLJ0fBPlJeNnySSKMIP8oh3/hUbZW79CoBzBgQ/fPSq+11cu,iv:jcef8ZWxFPh3aC6f/JfPIozx2G4ncPin2fUzfIGbTNQ=,tag:V2Xv/AQPzNOBVA/at+K0cA==,type:str]
    admin-email: ENC[AES256_GCM,data:7jbS4wABSuHOYWMz7OnorNZIdB4X8p/qkg==,iv:TU6Ormny74DWhFGUx0j/u6FuCLD0EpTWIrQ6DTU+nmo=,tag:fpbNNGIMRB2qKoMn3q6ySw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieFRRV0ExSXBDcFExVU5y
            VEEwKzU3K2hlYzRTeXEwUERKcE92QXNhdERVCkpCaFpIcUR3allScHhnYjFqZU1S
            MVEzcHIzRDZsaitEelEreTRpSmwzdDQKLS0tIFpjdVdoVExsL1hLSE1LaXVmZlRL
            cmZXOTVIeTBvZjhXNXNwOFMxbWZsZUEKSQzK/hMV/zSDbKvvUAyZ7FI7uwBcgWyX
            6bZM4ai7SxmVbtUZ5ReD5lSCW+XKB7VbsOS8wnyvmSV5MXD5GveP6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T12:35:34Z"
    mac: ENC[AES256_GCM,data:AFXOl2+q4GzBP4PkDoNmkPltpYUOB5jHIDxhMOJqBQbhRB0Wk0N4dh7H+Fnwyo0sf3qjYCoO9QMux+2fQ6oTMb8lHFp4rk36M5HWHWii8J3tkwH525bn8H6Ohi9/9mBsXU5UnAKGJ386oHSPpw8id2Vv77F6AV1u+BWdFV3qFEs=,iv:KEGswZkmTnEFjcTqkbn6wOHHcREEybBCAs4IzAQ91Zs=,tag:2brlCGdSRl01IKPcDDX8sg==,type:str]
    version: 3.13.3
