apiVersion: v1
kind: Secret
metadata:
    name: moneymatter-secrets
    namespace: moneymatter
type: Opaque
stringData:
    APPLICATION_JWT_SECRET: ENC[AES256_GCM,data:SeKxLFbprQvRKWuN/ENXgyUfC4yJtemiXvCaF0x4UtavytGtENjUSnVQLPE=,iv:5Lm4jBuHgIKh26b//gHHdWeuaf00/sABTa56CXlymBU=,tag:5a0a6OutmVeKtgKqzQbPvw==,type:str]
    APP_SESSION_ID_SECRET: ENC[AES256_GCM,data:15F8yzkIMa984KPX7vuxFQXvOGDlcHVTknt8ObeTluI/jCRIKKkIO65d2UQ=,iv:neQMMiHpgIfgzsS7g2f8Z5Exovk6qWFhGQWPGW3ma3c=,tag:B+osPedBEea3boU3yZIVag==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:hkVBi/zg1DiM6ckaF0Sq9Upey3dzOox3Y80krNOFqPpvFQClfPVos13QYV0=,iv:MniBQSFb31VuV3hCp1J2CUhCa0bnBbcyVTmk+5UxAG8=,tag:CHHNN8tqguuJH/rIxnZj/g==,type:str]
    APPLICATION_DB_PASSWORD: ENC[AES256_GCM,data:NwCKAWosccEoffqP06U2ta4zUzFLHh5kPcDIAI8jDg==,iv:UDEdfEXX15DAzr/njbI9c9uMdDqjG8R5pEGxw71X4TQ=,tag:VsNBliNfw+uG0BKiHY5gsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWjJ4NHJTR2ROdDd5TEZM
            cFZjVGNPdnFxdlM1ZUZVbVByRE0rQUl5V0RVCjhtMnNOdmxDYk44SHNHUEI1bDQ0
            ajgzdS9ZNkRqSzNFMlRlajBld3l4MVEKLS0tIFI0U3ZKSjBQZXNLY041UEdJa2la
            N0FzL1VMNyt5UGd4NCtSQzJ5MGVNQ2sKtRHNAsvD86+AxLBKAteFBCG2IAD0/eXH
            xi5a7Wu4D2e+VmHhCrp5T52pT2SBTxe0pPu7N+jzb7YUbz1pMF6H4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T16:46:02Z"
    mac: ENC[AES256_GCM,data:zMPl1forlhwoal6S0BbqHKDiKeuF7CUlpJ/ZvpwfdAYQgsfnoQ2OJY+8dx62pO1B3imDik8loBdap+MsPWeMGkvYX3o77gw4AuiganPfOZNpIQnwt2zvqn1ux/CxXxaIrjQGvFmDnaL8LPjEjZf4LeudaYqnMUJ73EpPBl9croM=,iv:Qd2ezAxcnC7hmfWffV9QZMdM/Uk8voISwk78Uv8WsT4=,tag:8Ruv1rKxZrlM+M7QqP4ckQ==,type:str]
    version: 3.13.3
