apiVersion: v1
kind: Secret
metadata:
    name: homarr-secrets
    namespace: homarr
    labels:
        app.kubernetes.io/name: homarr
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:Qb55svYhwCpCEYkRpPiAiBY5buNXMynAhle0zDvFtYhp4BCHYUCHvz1HMBTJSeqU0y//vLesjqXjHVJ7b9w/uw==,iv:CM4aZyn3rpM4Euhk4pg1jkloRTpoBnu8PW15RiD2su0=,tag:nSY7pCKPZtPgOEmCDJIgNA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:WmXYzamE1nYXMK6t/bFnAE6FcJ2qg4374bsjpepmzY8TR0D50ERGlP9V0c3gBJayBtZuOh29yn2Wfa3Cpo5dsH6/ZRAuivdNJn4Pv6u0HG5KG78NptPXKMMuBCY6oY5agL3Wux7x3QXjYSe/QMaEIVXJ7Vxb0Tcf5Y0e+kZqg40=,iv:sMpke+ayUFxXdQawGM7yvlYe6s+EiMhMuQzorGhtLQI=,tag:nUBG/jnej/mVl5aNmAlOXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYTNYMkdBdy9QR2RKMTN6
            elkvTVBja2MrNksxN0hVNXArQW1FT05zSDFFCjVTSnRObkNjSEVwek1ZVW5ONXcw
            RXZJdHhWN0hIOUd5Z0JMVXdEeC9sU00KLS0tIG5pK2NjdjZ3RVpNY2ZnYk96QkdC
            UldVc0ZpbmcwS2JYWUNWQWQzQWhiOTAKCBpxlHdk6IBoCl/umuo3velUZexwLPek
            qNOtp11xuYsn5/pI2qJsCA2MYOy88p1ozFWUDadL6fTm+7w/thm4Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T01:34:21Z"
    mac: ENC[AES256_GCM,data:9KN8z+Z5e03zcoa2GvTxURLq8/df5q4jSx+2q/jfyiS5pZz+MZbfWaHppJA1nZQ//HcuNEemyNUV4c/WJOWZK5lLJOWbVYfE2On6jE0paSLCdsNNerKQuOHHPcU/5sQqGrJoJ74Sm4Vle/RPHbIY5I3RYMYoBoXIXjuDf5L9iX0=,iv:qi/Mk1ii1Tc/pMW/subCT1EwbpMfnIMniYpRhdmQN5E=,tag:/sGefTlfsNhs3FVNyGabnQ==,type:str]
    version: 3.13.2
