apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:JZExgsetOLnZWUtStwE+N4R7ktDrWDlz8UzmI0XY/dW8hu6f75LhJdXC5gWtZbjWdv28c5k=,iv:vj69JQm2VQ86qjyGNXZSyFyRTNx0Ae7vCZIj57n647Q=,tag:GU7BVEfI2VBsbiP8r5pSWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbXpVVnZhUHJSTGJQTjF5
            dlpoOXVWZjk0aHNSclkrUHgvZ2VHcHJ3NUdFCmVreTlYR2V6VmFrWDdOYnVRMC9z
            dWJLQnRiNnFRSy9yRjhSMFh4S3FaRFEKLS0tIHUxV1pzNjN0Sno5ejhzSXNnTHZU
            ejFlR1FCcEJtMXVFbHROb3pyOHl6dDQKTpkLEjtOH85Tll5re3aMasOmzdtnAWfJ
            ny1RqzyWx9Ma0+mNUQvfNPzOY9mdPJvBYPK1SH1AW9/7PgIokIusYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T15:40:07Z"
    mac: ENC[AES256_GCM,data:wy1e59RGgrUb7HHaDIGHdwjjOLMTDyOQvl3tHSRLQ1u1ch3rsdcWalR5t2tA+5Y6Fjynzfxu2JxVk14dtFoCXT9qcznSl/Z55ouu7JCg0bnUA9TCZ6NtZ45xm03Vnp3e7MrWRfReap5c1hnCzdOoQdse6/c+Y3D52bkqWedXrl0=,iv:ee1YEMvjduNmT1NAMx6zhXGWMCr/1SiQzvAYlAqapOE=,tag:4SwtXzgTSZyTM7B9rX7BCA==,type:str]
    version: 3.13.2
