apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: cilium-lb
    app.kubernetes.io/part-of: fleet
  name: apps-default
spec:
  blocks:
  - start: ENC[AES256_GCM,data:j1ONd19au35FbctJqg==,iv:49P/3qohVYBf41TYGs6YOmZ+3gDN/xKtNJdp271Izsg=,tag:zoc3upmtfXmzoqbgfrXUpw==,type:str]
    stop: ENC[AES256_GCM,data:7gl/iNiw8VEogJ52EA==,iv:mkJZpG1eJYhinzeIX1tPNT2uRiByLiVnoigu82OYJAk=,tag:BgN94stv1WBm2qRs7hh0NA==,type:str]
  serviceSelector:
    matchExpressions:
    - key: lb-pool
      operator: NotIn
      values:
      - ingress
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV0dlbWhlM1N3VDJ1eGts

      TG5jQ0kxN3ZsVjFmTTBUN0NqbWxVdU9XdTM0CjdQYll3Vy8yRXNwMHFzY1lSWm5a

      dTBESHVHQlVFM2VrOEZNMTkrZDZDV2MKLS0tIG1VY3Z5bjRJcHJCNlpQZTFqQlR6

      RE9KT1BPc1ZKa2hDa1dwZjZ5SHhDNmcKT07O7/ytebxeJhRd0lIsiygUOmLCEBUT

      Bm23CopFb3OQ1p9DYre9OV7grWi6C7oSr6r09Pr2/+shU6sOFwgn2Q==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
  encrypted_regex: ^(start|stop|cidr)$
  lastmodified: '2026-09-13T12:40:13Z'
  mac: ENC[AES256_GCM,data:ZGs2Lhwe2xfkJ7GGcX7KOs4K072u1JBT1Hxqgaee+LxY8uKiYzQCk9+Q4H+semVb3DlRhHmT4//LTc/KRLffFRI0vUdaJ3LeLZWRLr5Xomlkb2Kd5TtbcVWQaHjZT6M93OzHGLq+iYszJNJFKgQlgKXeCyGOKaepLuDFlMfpNok=,iv:iZnqoAcZZ51V2GHKIfc14JZttLE+dd4lZamLOm9gsaY=,tag:5cpE9h1vuzx7JQA3+apVjA==,type:str]
  version: 3.13.3
