apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-log-config
  namespace: matrix
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: fleet
    app.kubernetes.io/managed-by: argocd
data:
  log.config: |
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    root:
      level: INFO
      handlers: [console]
    disable_existing_loggers: false
