apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: cloudflared
    labels:
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:NL3BTlqOvak96mwOjbS2NipCGTGuGv5vn5joeQV2bUV9+neJFKHZk2QUGYa+SzZJnb5uI+JSVfWz1wPkbE+PxhQxE4Z1v7lI9ZEIeQBKYCNj2ooCBeEpunVBOfNkuTWWdGFUy+wvSsZPh52dPQPbcCN6lwZ1E1IwDAjbwThP7FckknqhVGQB/JOsI1lP3jHjeG4nVy5RX5hq/ceBHImr9XE5jcKnDdLQc9fPkYxYN6U/F8sOSHS7GJnBG3loaDFYv6iugxJyMpZcuZ9/038Q8V5b6cpVTe3beWOyrNpHQfG5M8jzoQBXm4NEIs7oLPnf6gze+zoW1hU=,iv:NjUJCe+xh9l9XSYTjv8aJ2qg9hfEsGhHRxw4P2B998Q=,tag:edzE1s0Qy1Lq2NohJIr+/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcmNWZXpiU0pGRi9KSFVl
            ei9KN2YrbUl2aERleWV0YVFnK2JuWExVdGg0ClRCNVBsb05aUlBDNlJBVDFyZS9K
            L21KLzRValU3OE5FRGd5WXFDWGhPb00KLS0tIHUrdXYyY3U4eEhjbkg1TnlJd3lL
            SnZ1cG1FaWxJcE9FYmNJSk5vcVFxNEkKdLD31/ykpFRM8949XcMmQL6iBX5ShXGT
            OCj+Iq43byofHGb27n9+EBronzREs8+gGYEoBfvRhif4AEw6X3rauQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T15:59:36Z"
    mac: ENC[AES256_GCM,data:QVYbYja93k9gjo2TFP0sqZIYH1giTOaTkjGUPDmDB7WzPAn2AF7nBSIaf50AmQ3Jp9LaCS+64TitevHt/0OX03TlIpPGd5e75/IkadJQ3fWLlP3T5JJ65Nv6lwIa3HndyEZfWf4qif/rrgo3j7mmS7xjopVg+ZcZTw3tSqcxoXI=,iv:xuCYGxiQQkMMl3rVfmqngx01B4KjD/ySmMCg4n22vrQ=,tag:Y01A6+MBe73NOB3QbPoIPw==,type:str]
    version: 3.13.2
