apiVersion: v1
kind: Secret
metadata:
    name: mealie-secrets
    namespace: mealie
    labels:
        app.kubernetes.io/name: mealie
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    pg-password: ENC[AES256_GCM,data:KOLu+Quod7uhkoKZ7ZodYP37suUnxjISUA+/eLnSEIY=,iv:94f5cEvUW+8hgd48mzHnyQJhO/ViH+AAxrR7me4qDkI=,tag:aWe8mkytoQG8EK+MEjaRjQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:cao85pWFJgFkAUM/39sDXOMBtRtaVNeLg1sJGnXM/Vr/VHyGKhs2NptLKo48kXTFiWAdblQ6S53358M9R8nr7YIKqwcLqN4ji4ph3YboW+eXEB2UiNcSe0akGhXfCDHlIYfGeDYJ0wAMHFFRAX2Bf6HBRZHQ0wXhIKQacEFour8=,iv:Tv/w0xjefoloQX0K4D0GrW1k6vhsrwriOtT1GUUohsc=,tag:oKKEF4+WLOurbYUC3Q3E5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eFRhN2ltK3BvZ2g3RHpN
            cVhHbmhkcHdpbldtd1hpSE4vc0JXcGNPcWhvCm8rTnBEQlRpOXNhck9TaXp2b2E2
            NnlUVGZ3ZVBwU2dKUjF4UmtHSnFGNG8KLS0tIHhPUVdsVFBlZzZaSFBUVVVjdG1w
            QXBzUVhBeWx1aUNzSzhkb0pLOHV0YncKKuQ+J4Gl4CzHb0Tlno/kSJcJWccr6zRj
            F5BMYszRfZd4MxcYIo1n2qqId9Cp8Dn4D4QAsTIoarg/GpmpZSgYWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T02:08:23Z"
    mac: ENC[AES256_GCM,data:/r3pCvcVduSs4cHDWuIbK9H3+kiRzg7xCjS0RNyZ5LdbsOGsxdItXAq4jY49S2jsO03Q2F1ScEG8g137eFE3Ob1YZLsJBkpEMg6dMPLBgiendFVznG5py5jeuLbfDr2Q2LsnyVoxTE3dxg0BqxT/QIbQNGq8WqlP/Qi4CIBnnXo=,iv:SSW0cZ/h2JMeu2LuUm83MDX7FB8MCFO6rIJbWSfrjQ8=,tag:TLgRIf8MBhdX7o65MGmlhw==,type:str]
    version: 3.13.3
