apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: longhorn-b2-backups
    namespace: longhorn-system
    labels:
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WHe97t6tQzUI6avaWvn3qqs5HcxRzjaC9A==,iv:s+FM/B2K3T2LL163puAyaUcTs0b2PgF+51xLAhIO+gI=,tag:P5OsJEl4s7KaKvQXCaw09g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:B8KVibHSD4xS39SGqCXKfzMzFEKLAvmTsXEmgSl4Vg==,iv:k2ovRbSu2CXSAO9ijgZ+mP+8VDHGpr46J1jBM5jHRPs=,tag:Zlgq0vbRUwbmT+kjduYdaQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Y/TIqSToqOTaa4i8mtJAa5WyFst3Ihqc0RJcxgqJKfyFOgM7e9M=,iv:w3a+DdomhTAYyKQr7jnX5LKLwHP6uP/aTznaFrRE0O4=,tag:mVuZ83QLxlBBaZ8i26AShw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcTM4OUtETDF3WWV1Ulgx
            anUvbWpWc1pWV2ltNEVjWS9DRWFmZTRjaGtJCkhCQkVWbFArS0p5ajJkZFRoTFdW
            ZHExc25JVUhLNkt4N0EwWExkbE00RlUKLS0tIHpkbll6VDhnM0U3OHNzOUsyM01W
            aVoyUUQwOFZYZWRtbkthMy9mb0piODgK0gVBbBYXtqITA27wrh9b/oHhcKCBYskZ
            VnOMjx7mQdsJ6PmDe8TWl//wMtEMGfztHBtDPalduZltNqIinBy11g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T19:19:19Z"
    mac: ENC[AES256_GCM,data:whKZhPVEUJj5fLGJT+hEFbrCv173a5Ja44Alqbyt+C9mcwySnIZu46RoTOdIltW7qjDCWeQxVaIDZyjqPL9WxQ7OhOyvyLrFRmXGapY1EiQcAYsW7/BCupYseDiNftnuhf+XPaMqdLVMcqenIwU/p4lWb4c42X9xu27vMKCfVLk=,iv:eZHtmy9TAVDgSe2kNDvN400hUHf5D4QFkIlQrzc5Y5s=,tag:Ofu6Y1LKNvuX6BBAUnHz4g==,type:str]
    version: 3.13.3
