apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
    labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/part-of: fleet
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:RZEJs53fUssaBR5cwSlMRUBfMa1rDs4qpmL6xaONxhD7n87TXMi4VY78Pge0VWdYF+n4DQucmxLklA9QnH70KA==,iv:TFyobW9j9J8OYMQTyjFP72oRKgijU7c4VuCrNSsTJOI=,tag:NqLJsHzVU+g/fxAem/Q74Q==,type:str]
    postgres-password: ENC[AES256_GCM,data:3eZdqiV9PpOZWeutyv50mJxsGy327mkxwPk4m7iMc1UWT8+YHVHA9Ze7mpMQlXll,iv:KxWHVjI1NZYIzh5qvfsoCIO1h9hNK+POqmBQ0AXwj6o=,tag:jHcYv4lP5YcoPe4cl1tmGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM3p0Y0YycktWSm9seENu
            Z3diTFYyNDR6NFVvWFlweFUzclpjTnZob1ZRCkJtWmhEWGZ3U3pVcUppZXNUNUdX
            RnRnMWcyRXRqZ0l1YUlTVklhVEY2RjAKLS0tIGFYUGNZN25FMktzRlRBZElQRnpZ
            Z3MvYUE5SXcvbUJEdnZ4eEgzTzFlUU0K/SMWB+GHamZN+Sf+jU4PMyI+M54JtEAm
            xoLMp6cB1LQZQwjU/x6YJ9oNCzk1sAOIa5A0RKVWZUFHC07pQbgHVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w5yapjkwdf2frzuevgu4548ntr77dma9eu3kqmypfzguhf9ul3ss8rsghc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T21:15:30Z"
    mac: ENC[AES256_GCM,data:1cq1sP3b+WeEBaT8YVNETd/1im1g4KYgAeIL7M0EOJNxAD5VbaC0eJLqgKKN2mj+q5bEjpokiSFbDdBdCzAd8R7hYGFb8U1Fv4d2JX8Tz1kko5oLJcZKhK/Mn93Ighc8EbRidb6e1PXlWaGSdWi4c9F2ZP/Qs39KDHtF13Z7tx8=,iv:GQIR5YFxwXGebSFESnulVNxDNkUUmQB9j9Uv8Xc0nUU=,tag:h7TDyO8LQDN59yS6CVjTRg==,type:str]
    version: 3.13.2
